### ISSUE TITLE
Fix C# and Java coloring

### ISSUE THREAD

**Issue by akamud** [akamud/vscode-theme-onedark#1]
Right now they are broken and not useful at all.

**Comment by techniq** [comment]
:+1:

**Comment by txchen** [comment]
:+1: 
I am using this theme, thank you!
Any updates on this issue?

**Comment by akamud** [comment]
Yeah, I'll work on this over the weekend.

**Comment by nbrew** [comment]
Just ran into this issue myself. Any progress or pointers where to start adjustments?

**Comment by akamud** [comment]
I'm so sorry for not having this fixed yet. 

I need to find how the tokens are represented in VSCode, usually inspecting the editor via Developer Tools inside VSCode itself, then I use the token name to apply the correct color using the `.tmTheme`.

Do you use any themes that works fine for C# and Java? They would be a great place to start.

**Comment by nbrew** [comment]
Thanks for the theme port. No worries about it not being fixed. Developer Tools sounds like a good place to look for tokens. As for a working theme, Monokai Dimmed seems to have methods and method parameter tokens styled for c#. If I get some additional time I'll look into the issue but no promises. :) Thanks again.

**Comment by akamud** [comment]
Thank you for your patience, [One Dark 0.2.1](https://marketplace.visualstudio.com/items?itemName=akamud.vscode-theme-onedark) is now out and is much more like Atom's original theme for C# and Java.

You can see a sample here:  
![image](https://cloud.githubusercontent.com/assets/954102/12738072/7ea2b500-c93c-11e5-9244-55cbbb0eceb9.png)

Thanks for using and please report if any other issues is found.

**Comment by nbrew** [comment]
Sweet! Looks good for c# on my end. Thank you very much!

**Comment by txchen** [comment]
Thank you @akamud ! It looks great!

**Comment by akamud** [comment]
I'm closing this for now, if you spot any differences report and I'll fix it.
