### ISSUE TITLE
Add "one light" theme

### ISSUE THREAD

**Issue by ThomasWeiser** [akamud/vscode-theme-onedark#10]
That would be great!

**Comment by NKjoep** [comment]
I agree, that would be great! I think vscode really lacks of a decent light theme.

I tried to port my favourite color scheme (mac classic) from atom to vscode but I gave up when I saw how much time it requires to test it.

The sad thing is there's no fast way to test the namespaces or the definition specified in the theme.

**Comment by akamud** [comment]
Indeed, this is something that could be improved in VSCode.

I'm planning a way to make the Light Theme easier to derivate from the Dark theme, so I don't have to do everything twice, it would take too much time.

I'll report back when I progress on this.

**Comment by akamud** [comment]
Ok, this is finally released in the [marketplace](https://marketplace.visualstudio.com/items?itemName=akamud.vscode-theme-onelight).

Source code [here](https://github.com/akamud/vscode-theme-onelight).
