### ISSUE TITLE
Adding boolean keywords 

### ISSUE THREAD

**Issue by caralse** [akamud/vscode-theme-onedark#100]
**Please provide as much information as possible, usually I need these information to actually start working on an issue, so try to fill as much of these as possible**

## Sample code

```
--some keywords such as
or not and

--should be highlighted like
local
```

## Filename and Language selected

Lua
code.lua

## Atom Original theme Screenshot

<img width="181" alt="schermata 2018-11-05 alle 19 47 48" src="https://user-images.githubusercontent.com/44784474/48019780-87576200-e134-11e8-8588-ad9bcaf81b01.png">

## VSCode theme Screenshot

<img width="188" alt="schermata 2018-11-05 alle 19 48 12" src="https://user-images.githubusercontent.com/44784474/48019817-a229d680-e134-11e8-9337-ccc2084d0825.png">

## Versions used

* VSCode version: 1.28.2
* Theme version: 2.1.0

## Extra information
None

**Comment by akamud** [comment]
Fixed in 2.2.0.
