### ISSUE TITLE
How can I enable this for C++?!

### ISSUE THREAD

**Issue by bomcon123456** [akamud/vscode-theme-onedark#101]
So I'm new to Visual Code and started to find some themes to work efficiently, this theme just blows away!
But here's the problem, I'm currently writing C++ code and the themes seems highlight only the "significant" one like: variable types, class name,include,... But not the variables name, function name or some available-only-when-included like c++'s ADT.
Can anyone show me how? 
Thank you very much!
Here's is what is currently working
![image](https://user-images.githubusercontent.com/20278911/48466536-c793a000-e818-11e8-9a39-90d682772dd6.png)

**Comment by akamud** [comment]
Hi, can you confirm that the lower right shows your file as C++? If it is, it may just be a case of the extension not providing the right tokens color for C++.

**Comment by bomcon123456** [comment]
Yes, It did say that it is C/C++. So in this case, what should I do to fix this. Thank you for you reply!

**Comment by akamud** [comment]
Can you provide a sample screenshot of this same code in Atom? Also, can you paste the code here so I can compare?
