### ISSUE TITLE
backslash in strings c/c++ hard-to-impossible to read

### ISSUE THREAD

**Issue by tcwalther** [akamud/vscode-theme-onedark#11]
In C/C++, the following string is displayed nicely:

```
"\n"
```

The following string, however, isn't (note that it is not a valid escape sequence):
```
"\ "
```
The backslash is coloured in the standard background color, and is thus only visible if the line is the active line - even then, it's *very* hard to see.

It would be great if the colour was changed to something readable - maybe red, indicating that it's not a valid sequence? For comparison, here's Github's markup:

```c
"\n"
"\ "
```

**Comment by akamud** [comment]
Thanks for reporting. I'll see how Atom handles these cases and I'll try to keep it as close as possible.

**Comment by akamud** [comment]
Hi @tcwalther, sorry for taking so long. I just released a version 0.2.6 that fixes this. Unfortunately VSCode won't render the red background, but at least it is readable now.

Thank you so much for reporting, tell me if you find any more inconsistencies

**Comment by tcwalther** [comment]
Thanks a lot for this, @akamud.
