### ISSUE TITLE
Icons on left bar disappear when theme is enabled

### ISSUE THREAD

**Issue by justin2taylor** [akamud/vscode-theme-onedark#110]
Just installed on VS Code 1.30.2 on Mac 10.13.6 and whenever I enable it, the icons to the left disappear.

![image](https://user-images.githubusercontent.com/10479769/51874719-f6e58380-2316-11e9-9ae3-1d77e0cc9ccd.png)

Tried restarting my computer, re-installing the extension, but it's still happening.

**Comment by akamud** [comment]
I could not reproduce this neither on my Windows nor on my Mac. This only happens to my theme? Are you positive your VSCode installation is not corrupted somehow?

**Comment by justin2taylor** [comment]
Okay, just installed the Insider's build of VS Code (1.31.0) and now it's not doing it. Must be some issue with 1.30.2? Anyway, I can roll with this for now. Thanks for the quick response @akamud!

**Comment by justin2taylor** [comment]
Looks like the issue is my graphics card, not your extension. The UI in other apps has started to make things disappear like this too. Even though it kept happening when I'd launch your extension, possibly cause it was a 3rd party one while the others were built-in or something.

**Comment by akamud** [comment]
Aww, hope you can fix this. Thank you for your response!

**Comment by justin2taylor** [comment]
And the GPU died completely today, so that was definitely the issue. Have a backup one so all good.
