### ISSUE TITLE
[Question] Difference between OneDark-Pro and your OneDark

### ISSUE THREAD

**Issue by kanlukasz** [akamud/vscode-theme-onedark#117]
Hi,
Like in the title - what is the difference between:

- https://github.com/Binaryify/OneDark-Pro
and your
- https://github.com/akamud/vscode-theme-onedark

I am curious, because at first glance it looks the same.
Is there any important difference? or anything else?

**Comment by akamud** [comment]
They are about the same indeed. I think the main reason the “pro” exists was because he supported workbench theming before me. Last time I checked mine was more consistent on syntax highlighting.

**Comment by kanlukasz** [comment]
Ok thank you for your response
