### ISSUE TITLE
How can I make my vscode look the same as in the screenshot?

### ISSUE THREAD

**Issue by Sturmfrei-I** [akamud/vscode-theme-onedark#118]
## But vscode shows:

![2019-11-27 10-02-42 的屏幕截图](https://user-images.githubusercontent.com/48857232/69687269-48a89700-10fd-11ea-9ff0-03a70988d332.png)

## Versions used

* VSCode version: 1.40.1
* Theme version: 2.1.0
* OS: Ubuntu 18.04

**Comment by akamud** [comment]
I use Fira Code... macOS font rendering on a Retina display is also way smoother, that could be the case for the differences.

**Comment by Sturmfrei-I** [comment]
OK, Thank you, I'll try it.
