### ISSUE TITLE
Update due to the new semantic highlighting setting 

### ISSUE THREAD

**Issue by MohamadKh75** [akamud/vscode-theme-onedark#119]
Hey

As you can see in [this issue](https://github.com/microsoft/vscode/issues/92308), there is a new `semanticHighlighting` which breaks the theme and they asked theme maintainers to update the theme.

[changelog](https://code.visualstudio.com/updates/v1_43#_typescript-semantic-highlighting)

**Comment by akamud** [comment]
Thank you for bringing this to my attention. I'll release a new version fixing this issue.

**Comment by MohamadKh75** [comment]
Thanks!
It would be great if we cane have https://github.com/akamud/vscode-theme-onedark/pull/95 in new release too 😁

**Comment by akamud** [comment]
Ok, it looks like this was not intended to be the default, so the [next update](https://github.com/microsoft/vscode/issues/92308#issuecomment-597899153) (probably a 1.43.1) will disable this behavior and give us enough time to update our themes when we feel we are ready for the new tokenizations.

I see the [code is in place](https://github.com/microsoft/vscode/commit/41a4adb47b44fed360105ffb68d6ddf0778b25fb) already to disable this behavior as default, so we should just wait for an update and everything should come back to normal until I have the time to update with the enhancements. I can confirm this is the behavior in the insiders already.

In the meantime, as people already said, you should set this in your settings:
```json
"editor.semanticHighlighting.enabled": false
```

I'm following the other issues not related to this.

**Comment by akamud** [comment]
#95 is released in 2.2.0.

**Comment by AbdelrahmanHafez** [comment]
Is this fixed?

using Atom One Dark v2.2.0, VSCode v1.43.1, with

```js
"editor.semanticHighlighting.enabled": false
```

Current colors:
![Screenshot_323](https://user-images.githubusercontent.com/19984935/77248901-d3ca1180-6c45-11ea-9918-50bed3c312f4.jpg)

As far as I can remember, object properties in JS had the same colors as the variable `a` in this example.

Am I missing something?

**Comment by akamud** [comment]
As I commented on #123, this is the new behavior in Atom as well. I give more details on how to bring back the old behavior and the reason behind this in the original issue.
