### ISSUE TITLE
How to active this package?

### ISSUE THREAD

**Issue by tp** [akamud/vscode-theme-onedark#12]
I could install the theme just fine using the command from the gallery, but it did not active automatically in VSCode 1.1.

Adding some info on how to active this to the README would be very helpful.

**Comment by akamud** [comment]
Hi, thanks for using. Themes don't activate automatically, you have to go to the commands palette again and choose `> Preferences: Color Theme` > `One Dark`.

I'll consider adding this to the README, thanks for the heads up!
