### ISSUE TITLE
When i load first vscode it shows normal as it should be.But after 2 or 3 seconds it becomes look like one dark pro theme. As you can see variable names are red and so on

### ISSUE THREAD

**Issue by nesibeyyubov** [akamud/vscode-theme-onedark#120]
VSCode version is: 1.43.0
It is a javascript file

![dsfsd](https://user-images.githubusercontent.com/55137572/76495179-c2b42000-644f-11ea-9707-c75b1fa60f54.jpg)

**Comment by sgriff96** [comment]
Also having this issue

**Comment by bcanseco** [comment]
Running into this too using v2.1.0 of the extension.

VS Code:
```
Version: 1.43.0 (user setup)
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:47:57.235Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763
```

**Comment by nesibeyyubov** [comment]
`"editor.semanticHighlighting.enabled": false`

guys i solved this problem by adding this line to settings.json file. It is a problem about version 1.43.0 of VSCode.

**Comment by akamud** [comment]
Similar to #119, I'm working on a fix.

**Comment by akamud** [comment]
Ok, it looks like this was not intended to be the default, so the [next update](https://github.com/microsoft/vscode/issues/92308#issuecomment-597899153) (probably a 1.43.1) will disable this behavior and give us enough time to update our themes when we feel we are ready for the new tokenizations.

I see the [code is in place](https://github.com/microsoft/vscode/commit/41a4adb47b44fed360105ffb68d6ddf0778b25fb) already to disable this behavior as default, so we should just wait for an update and everything should come back to normal until I have the time to update with the enhancements. I can confirm this is the behavior in the insiders already.

In the meantime, as people already said, you should set this in your settings:
```json
"editor.semanticHighlighting.enabled": false
```
