### ISSUE TITLE
editor.renderWhitespace doesn't work

### ISSUE THREAD

**Issue by AlencarGabriel** [akamud/vscode-theme-onedark#121]
## Sample code

```
any code
```

## Filename and Language selected

not applicable

## Atom Original theme Screenshot

![image](https://user-images.githubusercontent.com/10109480/76544388-b8e9e700-6466-11ea-8ad9-beab9a765dcc.png)

## VSCode theme Screenshot

![image](https://user-images.githubusercontent.com/10109480/76544439-ce5f1100-6466-11ea-8844-49413f0a93a9.png)

## Versions used

* VSCode version: 1.43.0
* Theme version: 2.1.0

## Extra information

In version 1.43.0 of VsCode, the `editor.renderWhitespace: selection` configuration was made available. But apparently the rendering of the TAB and space characters isn't being done in this theme.

**Comment by AlencarGabriel** [comment]
I was wrong. It's actually being rendered. But the color of the rendered elements is very close to the background of the code selection.

Should this treatment be done in the theme?

**Comment by akamud** [comment]
This is now fixed in 2.2.0.

![image](https://user-images.githubusercontent.com/954102/76709508-0b810880-66de-11ea-88e5-8abe69e2134b.png)

Please remember to disable Semantic Highlighting if you are using VSCode 1.43.0:
```json
"editor.semanticHighlighting.enabled": false
```

**Comment by AlencarGabriel** [comment]
Thanks for quick fix!
