### ISSUE TITLE
Add theming for side bar

### ISSUE THREAD

**Issue by chimon2000** [akamud/vscode-theme-onedark#13]
Would like the themes to apply to the sidebar, like high contrast.

**Comment by akamud** [comment]
Thanks for using @chimon2000, unfortunately VSCode doesn't support sidebar coloring. There is an issue raised [here](https://github.com/Microsoft/vscode/issues/3112), you could upvote it so they can prioritize.

I will update One Dark as soon as we get APIs for that.

**Comment by akamud** [comment]
hank you for your patience, this is now released in version 2.0.0. Please report if you find anything unusual :)
