### ISSUE TITLE
Json edition should be improved

### ISSUE THREAD

**Issue by robertohuertasm** [akamud/vscode-theme-onedark#14]
Hi,
I was trying this cool theme and I like it but when I started to edit a json file I realised that it was completely unusable. The text color gets dark and almost blended with the background color. No way to see what one's typing :(

**Comment by akamud** [comment]
Hi @robertohuertasm, thank you for using and reporting. Can you provide more information please? I just  opened a JSON file with the theme activated and I got nice coloring:

<img width="406" alt="screen shot 2016-06-11 at 13 54 08" src="https://cloud.githubusercontent.com/assets/954102/15986332/092d2f06-2fdc-11e6-8ea8-ea4c32fabb6e.png">

I need more details to reproduce your scenario.

**Comment by robertohuertasm** [comment]
When you write not using double quotes you can not read what you type. I know it's not proper json syntax but it would be nice to avoid this black color for the font.

<img width="363" alt="screen shot 2016-06-11 at 22 53 53" src="https://cloud.githubusercontent.com/assets/696981/15987405/8f28afd6-3027-11e6-8f89-fea678176d78.png">

**Comment by akamud** [comment]
Thanks for the feedback @robertohuertasm, I didn't notice this bug. I will release a new version fixing this.

**Comment by akamud** [comment]
I just released a version 0.2.6 that fixes this.

Thank you so much for reporting, tell me if you find any more inconsistencies.
