### ISSUE TITLE
What have you done? Suddenly this shit looks hideous

### ISSUE THREAD

**Issue by PINHOf** [akamud/vscode-theme-onedark#149]
Today I open my VS Code, with the same Atom One Dark theme I have for years and suddenly new colors pop up. I work with PHP, JS, Dart and everything looks different.

Why on earth now the "{" is yellow and "(" in functions is blue? How do I roll back?
![image](https://user-images.githubusercontent.com/6898403/167158300-598a3c1d-a5ed-4470-b122-b179545b5cae.png)

What is this? A disco of colors?
![image](https://user-images.githubusercontent.com/6898403/167158950-c2b6ff78-72c9-48c1-b4c8-82cfea2d568f.png)

I have few extensions; I didn't change a thing. Maybe VSCode updated and messed up everything?

**Comment by PINHOf** [comment]
**Solved**, it's a issue with VSCode, I guess some updates mess up with the theme.

**Related**:
https://github.com/microsoft/vscode/issues/92335
https://code.visualstudio.com/updates/v1_67#_bracket-pair-colorization-enabled-by-default

**How to solve**:
1) Go to "View" > "Command palette" > type "settings.json" 
2) Add the following lines in bottom:
```
"editor.semanticHighlighting.enabled": false,
"editor.bracketPairColorization.enabled": false
```

**Comment by akamud** [comment]
I'm deleting your issue because you were disrespectful. Next time you open an issue on an open source project be more kind.
