### ISSUE TITLE
Make object/property names red in JS

### ISSUE THREAD

**Issue by bdanmo** [akamud/vscode-theme-onedark#15]
I love the atom dark theme, so thanks for doing this! One of my favorite things about atom dark in javaScript is missing, though. In atom, all object and object property names are colored red, whereas in your version for VS Code, they are gray, just like any other variable or parameter name. I love this distinction that One Dark for atom brings between object/property names, and names of variables/parameters.

**Comment by akamud** [comment]
Hi @bdanmo, thanks for using and contributing. 

Someone else raised a similar issue [here](https://github.com/akamud/vscode-theme-onedark/issues/11). Unfortunately, for that to work on VSCode we need them to improve the tokenizer first. There is no way right now of differentiating those cases, so JS coloring is very limited on VSCode at the moment.

As soon as they improve the tokenizer I'll update the theme with these improvements.

**Comment by bdanmo** [comment]
Ah, ok. That makes sense. I do hope they update that. Thanks for the quick response and keeping it up to date. I did notice that none of the UI themes had this differentiation. That explains it!
