### ISSUE TITLE
Incomplete support of python keywords

### ISSUE THREAD

**Issue by lklabs** [akamud/vscode-theme-onedark#16]
Support of some python keywords does not match one dark theme from original atom.

For example, the following keywords (and maybe some others) are not covered: "not", "in", "and", "is"

Example in real atom
![real_atom_onedark](https://cloud.githubusercontent.com/assets/10778502/17933515/052348fc-6a1d-11e6-97ba-2452bdd803b1.png)

Example in vscode with current color theme
![vscode_onedark_current](https://cloud.githubusercontent.com/assets/10778502/17933514/05214f20-6a1d-11e6-8d94-855c645f7b20.PNG)

**Comment by akamud** [comment]
Thanks for reporting, I'll see if VSCode allows for customization for these keywords in Python and report back.

**Comment by akamud** [comment]
Fixed in 0.2.7.
