### ISSUE TITLE
How to change color

### ISSUE THREAD

**Issue by shaooping** [akamud/vscode-theme-onedark#160]
I love this theme very much, thank you for your working.

I use the one dark pro flat theme, here's a problem: 

When I write code, the header's color same with body,
![2023-01-12_235842_active](https://user-images.githubusercontent.com/37577427/212120038-1642d3d9-f0bf-4dde-81d3-68f6f16d9fdb.png)

When I click the desktop or leave editor, the header's color changed to
![2023-01-12_235734_inactive](https://user-images.githubusercontent.com/37577427/212121511-e558cf55-662b-4335-b649-abee987ed677.png)

 Now I want to whether in editor or leave current window, the header's color like the first one, I already try to change some code at
'.vscode\extensions\akamud.vscode-theme-onedark-2.3.0\themes\OneDark.json', but I can't find some  effect, I need your help.

Thank you again.

**Comment by akamud** [comment]
In the README you can find how to customize colors you want:

https://github.com/akamud/vscode-theme-onedark#customization

**Comment by shaooping** [comment]
> 在自述文件中，您可以找到如何自定义所需的颜色：
> 
> https://github.com/akamud/vscode-theme-onedark#customization

Thanks for your replaying. 
I find the way to change. Find One Dark Pro 'flat.json' and search '"titleBar.inactiveBackground", modify color, then reload the edit, it's working!
It's a wonderful theme, thank you!
