### ISSUE TITLE
HTML attributes not being highlighted in PHP files

### ISSUE THREAD

**Issue by NicholasPurdy** [akamud/vscode-theme-onedark#17]
Atom: 
![atom](https://cloud.githubusercontent.com/assets/4528390/18810709/2551e42e-826b-11e6-93da-819263b132e1.png)

VSCode with one dark theme:
![vscode](https://cloud.githubusercontent.com/assets/4528390/18810711/347acca4-826b-11e6-82da-67ee3e910a8e.png)

Is it possible to fix this?

**Comment by akamud** [comment]
Thanks for the heads-up. I'll enable HTML attributes for php files too.

I'll let you know when I make a new release with this implemented.

**Comment by akamud** [comment]
Fixed in 0.2.7.
