### ISSUE TITLE
Python decorator arguments not highlighted

### ISSUE THREAD

**Issue by vesauimonen** [akamud/vscode-theme-onedark#23]
### Atom
![screen shot 2016-11-18 at 13 30 55](https://cloud.githubusercontent.com/assets/1443031/20428732/47aa80aa-ad93-11e6-8773-fb2049cde9d2.png)

### VS Code
![screen shot 2016-11-18 at 13 25 16](https://cloud.githubusercontent.com/assets/1443031/20428711/31e7711a-ad93-11e6-9cfd-ea2c7bdf1a72.png)

Thanks for the theme! 😊

**Comment by akamud** [comment]
Thanks for taking the time reporting this. I'll take a look if VSCode can tokenize these cases and I'll report back.

**Comment by akamud** [comment]
This is fixed in version 0.3.

Thank for the patience while I fixed this :)
