### ISSUE TITLE
PHP code inside quotes in HTML looks like string

### ISSUE THREAD

**Issue by rteamx** [akamud/vscode-theme-onedark#24]
Here:
![2016-11-21_22-57-24](https://cloud.githubusercontent.com/assets/3108511/20489694/116aeab8-b03e-11e6-9d1a-be2bf3bea605.png)

Thanks you for the theme!

**Comment by akamud** [comment]
Thanks for taking the time to report this. 

I'll investigate and report back when I release a new version.

**Comment by akamud** [comment]
This is fixed in version 0.3.

Thank for the patience while I fixed this :)
