### ISSUE TITLE
Twig syntax colouring

### ISSUE THREAD

**Issue by pjhartin** [akamud/vscode-theme-onedark#25]
Firstly, thank you for your efforts with this theme. It is great.
I noticed today that syntax highlighting doesn't work on twig php templates, but it does on the default themes.

Example package that highlights twig: Twig Pack (https://marketplace.visualstudio.com/items?itemName=bajdzis.vscode-twig-pack)

**Comment by akamud** [comment]
Hi, thanks for taking the time to report this.

I've never heard of Twig, from my understanding you are editing a php file (effectively a `.php` file) and it is not highlighting? 

Can you provide a sample and more information so I can investigate what is happening, please?

**Comment by akamud** [comment]
I need more info to improve this, can you help me? ;)

**Comment by akamud** [comment]
Closed until we get more information.
