### ISSUE TITLE
URLs, JS Template Literal, punctuation/grammar Colors

### ISSUE THREAD

**Issue by pmbenjamin** [akamud/vscode-theme-onedark#28]
First of all, thank you for making this theme. It's awesome. 👍 

The colors associated with URL strings, JS String Interpolation/Template Literals, and minor punctuation characters are a bit inaccurate compared to Atom's One Dark Theme (see screenshot below for reference).

### URL Strings
In Atom, URL strings in code appear in magenta color.
In VS Code, they appear in a regular string color (green).

**Note:** The red curly braces `${...}` in VS Code is due to the [VS Code Atom JavaScript Grammar](https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-atom-grammar) package being installed in my editor. Otherwise, the curly braces appear in a regular string color (green).

### JavaScript String Interpolation/Template Literals
In Atom, variables in template literals appear in "red"-ish color.
In VS Code, they appear in a regular string color (green).

### Punctuation/Grammar (Minor issue)
In Atom, punctuation (e.g. `:`, `${}`) appear in teal/cyan, except for a few punctuation characters (e.g. `;`).
In VS Code, punctuations appear in white color.

### Screenshot
**Your Theme**
![screen shot 2016-12-30 at 2 53 13 pm](https://cloud.githubusercontent.com/assets/6811830/21573960/ce0ccf9a-ce9f-11e6-8b43-9b5a34cd16ef.png)

**Some other [One Dark](https://github.com/azemoh/vscode-onedark) theme**
![screen shot 2016-12-30 at 2 53 21 pm](https://cloud.githubusercontent.com/assets/6811830/21573961/ce0daff0-ce9f-11e6-9bce-f65096a7fde7.png)

### Disclaimer
Even though the other VS Code One Dark theme has those correct JavaScript grammar/syntax colors, I'd much rather continue using your theme. You have more accurate colors when it comes to other languages (e.g. PHP, Ruby, Rust, Go) compared to the other One Dark theme.

**Comment by pmbenjamin** [comment]
I'd also be more than glad to contribute those fixes (assuming you agree with them).

**Comment by akamud** [comment]
Thank you so much for taking the time reporting this in a detailed way. I'm on vacation right now, but I plan to fix all those reported issues when I get back.

Are those examples all on JS/TS files? Just so I can reproduce and work on a fix.

Feel free to contribute whenever possible, I love when the community gets involved :)

**Comment by pmbenjamin** [comment]
@akamud, yes, my screenshots are examples from JS files.
I'll see if I can do this in the next couple of mins.

**Comment by pmbenjamin** [comment]
One side-note, I see VS Code can change the "Explorer" color to white when you change the theme to a Light theme (so that the explorer side-bar matches the color of the main editor window).

If it is possible to accomplish the same with Atom One Dark color scheme, how would you feel about the Explorer side-bar matching the color of the main editor window?

**Comment by akamud** [comment]
The most difficult part about fixing theses inconsistencies is making sure the change did not break the coloring for any other language.

**Comment by akamud** [comment]
Right now you can only choose between White and Black sidebar colors, that's why I can't make it match the main editor color... This has come up before and many people are asking for this, they are working on a way to allow us to do that right now [here](https://github.com/Microsoft/vscode/issues/3112).

**Comment by pmbenjamin** [comment]
I don't quite understand the tmTheme rules (e.g. `string.embedded` vs `string.embedded.begin` vs `string.embedded.end` vs `string.inherited` ...etc). So, I'm not sure if I can figure this out at the moment.

I'll try to do some research and take a stab at it again later this weekend.

**Comment by akamud** [comment]
This is something I need to work on: I should have a Contributing file explaining how to figure out these rules and improve the theme.

**Comment by akamud** [comment]
Thanks for the patience while I fixed this, it is now much closer to Atom in version 0.3.

Please make sure you also have the latest VSCode version, it has much better tokenization, version 0.3 uses this. Without it there is no way to fix much of the issues.

Here is a screenshot of version 0.3 fixing the issues you reported.

<img width="511" alt="screen shot 2017-01-15 at 14 10 57" src="https://cloud.githubusercontent.com/assets/954102/21964081/94be658e-db2c-11e6-887f-b7c7e7ae6334.png">

VSCode still can't differentiate some things. 

Atom treats some functions differently, VSCode doesn't provide anyway to do that, so they have the same color. In the example below, `defer` and `populateList` have different colors in Atom, but that can't be achieved with VSCode right now.

<img width="494" alt="screen shot 2017-01-15 at 14 13 20" src="https://cloud.githubusercontent.com/assets/954102/21964091/cdaf5678-db2c-11e6-9846-ba6653aac74f.png">

VSCode also can't differentiate `const` from `var`, so this results in a small diference in VSCode:

<img width="318" alt="screen shot 2017-01-15 at 14 15 35" src="https://cloud.githubusercontent.com/assets/954102/21964109/1a778f0c-db2d-11e6-9dc8-8ef733eb4e68.png">

In Atom theses variables should all be gray.
