### ISSUE TITLE
Color sidebar

### ISSUE THREAD

**Issue by techniq** [akamud/vscode-theme-onedark#3]
It would be nice if the sidebar was color themed to match the editor.

**Comment by akamud** [comment]
Hi, unfortunately this is not possible right now with the api's available for extensions on VSCode :(

**Comment by techniq** [comment]
I noticed the sidebar had changed when switching between the default Light and Dark themes, but it appears those are the only two options :(

**Comment by akamud** [comment]
Yes, at the moment you can only choose the base color, there are other limitations too. If they expand the API I'll update this.

**Comment by hgouveia** [comment]
I've installed some anothers themes, and i noticed, for example "Contrast" theme change the sidebar color ,

can you change at least the sidebar background to match the One Dark background?

**Comment by akamud** [comment]
Unfortunately no, I also noticed "Contrast" changed the sidebar color, but this a native theme and they have access to more features than we as extensions developers.

**Comment by hgouveia** [comment]
Hi @akamud thanks for you reply, 

did you check OceanKit theme, https://marketplace.visualstudio.com/items?itemName=chipcollier.Theme-OceanKit ? this seems not to be a native theme , but im not really sure thu

**Comment by akamud** [comment]
I'm sorry, I didn't notice you mentioning OceanKit before. 

This is not native but they only choose between "Dark" and "Light" sidebar, those are our only options, we can't choose the colors exactly.

**Comment by hgouveia** [comment]
got it, hope they expand the api soon, thanks for your reply

**Comment by 50l3r** [comment]
+1 i'l wait for this improvement

**Comment by akamud** [comment]
Thank you for your patience, this is now released in version 2.0.0. Please report if you find anything unusual :)
