### ISSUE TITLE
Missing syntax coloring for Asciidoctor

### ISSUE THREAD

**Issue by sanguine8082** [akamud/vscode-theme-onedark#30]
Syntax highlighting for asciidoctor language syntax is completely absent.  

Atom Settings (windows 7):
![image](https://cloud.githubusercontent.com/assets/8801258/21943239/fa3405e2-d995-11e6-8196-0875bde0dc3b.png)
![image](https://cloud.githubusercontent.com/assets/8801258/21943258/0be502a0-d996-11e6-9ae5-87071357ce28.png)

Visual Studio code:
![image](https://cloud.githubusercontent.com/assets/8801258/21943282/2b4880e0-d996-11e6-8768-88a21f07ad65.png)

**Comment by akamud** [comment]
Thanks for reporting, I'll see what is missing and I'll let you know when a new version is available

**Comment by akamud** [comment]
I'm going to need more information about this, since I don't know what Asciidoctor is exactly.

Are you using any plugins to get support for that?
What extension file is that?
What language did you select on Atom to get syntax highlighting?

**Comment by sanguine8082** [comment]
Asciidoctor is an extension of the Asciidoc language if you are familiar
with that.

Here is a link to their homepage: http://asciidoctor.org/.

I am saving my files with the extension .adoc, though I believe others are
supported.

Yes, I am using a plugin both in vscode and in atom.
  vscode plugin - https://github.com/JustusAdam/language-asciidoc
  atom plugins - https://atom.io/packages/asciidoc-assistant

I suppose I never considered the highlighting would be an issue of the
language plugin.  It is strange though.  With the Monokai theme included in
vscode, I'd say about 80% of the highlighting works, but in several other
color themes I've tried, it drops down to 50% or less.

I would love to help get this figured out, so please let me know if you
need any more information!  Thanks for looking into this for me.  I'd offer
to fix it myself, but I've never attempted to write or read these vscode or
atom plugins/languages myself.

Thanks again

**Comment by akamud** [comment]
Thank you for providing all the information.

I'll install this plugin and I'll see what I can do.

Officially I don't plan on supporting coloring for languages installed via plugins simple because it is very hard to maintain, but I'll take a look first and then I will let you know.

**Comment by sanguine8082** [comment]
Awesome!

I appreciate even the limited support provided thus far!

I'm actually interested in learning how to work with these plugins, so I
can fix some of these things myself in the future.  Do you have a
recommendation of a good starting point?

**Comment by akamud** [comment]
Hi, sorry for taking to so long to answer, I was rewriting the whole extension after VSCode 1.9 changed the way scopes work.

I examined the Asciidoc language support in VSCode, and while I now have a better way of generating the colors for plugins, the plugin you use right now for AsciiDoc language support does not expose many scopes. I examined all the scopes from the sample you provided comparing it to Atom and you would get pretty much only list's bullets coloring, with any theme.

In order to get better coloring the creator of the language service must provide more scopes, then I can take a look at this again. The closer the scopes are to Atom's plugin, the more likely it is for me to support this in the theme.

**Comment by sanguine8082** [comment]
Cool thanks for letting me know. I'll drop a comment over at the language
extensions github page and ask for more scopes. Thanks for investigating
this for me so much!

**Comment by akamud** [comment]
Please ping back if they update it. I'm closing this for now. Feel free to reopen if something changes.

**Comment by sanguine8082** [comment]
FYI, here is the issue I opened with the language extension:

https://github.com/joaompinto/asciidoctor-vscode/issues/8
