### ISSUE TITLE
Issue with JSX

### ISSUE THREAD

**Issue by vkbansal** [akamud/vscode-theme-onedark#32]
<img width="864" alt="screen shot 2017-01-18 at 10 11 05 pm" src="https://cloud.githubusercontent.com/assets/5930351/22073342/19fdd572-ddcb-11e6-8b3c-95d8677904a8.png">

As you can see, that there is some problem while using a function inside an JSX attribute

The problematic code is 
```js
<div className={colStyles}>
        <TextInput label='Fuel Quantity (Lts)' readOnly
            value={(data.get('cost') / data.get('fuelRate')).toFixed(2)} />
    </div>
</div>
```

**Comment by akamud** [comment]
Thank you for taking the time reporting and sending a sample.

I'll investigate what's wrong and answer here if this is a problem caused by the theme.

**Comment by vkbansal** [comment]
Upon further investigation, I found that this noy an issue with the theme but vscode itself. Everything works fine in the insiders build.

<img width="700" alt="screen shot 2017-01-18 at 10 42 56 pm" src="https://cloud.githubusercontent.com/assets/5930351/22074780/880ea38a-ddcf-11e6-840d-f0cd3dc54208.png">

**Comment by vkbansal** [comment]
Thank for the awesome theme!!

**Comment by akamud** [comment]
Thanks for reporting back :)
