### ISSUE TITLE
Weird "chunking" of the background on a fresh install 

### ISSUE THREAD

**Issue by cjke** [akamud/vscode-theme-onedark#33]
I'm not sure how to describe this, but there is a weird chunking behaviour in the background when this theme is installed. 

I'm on the latest vscode and latest theme. Interestingly when I move the cursor about, the chunking jumps around. 

![image](https://cloud.githubusercontent.com/assets/884065/22494107/094a63aa-e878-11e6-8c22-c500ecb1a787.png)

**Comment by cjke** [comment]
https://github.com/Microsoft/vscode/issues/12473

**Comment by akamud** [comment]
Thanks for reporting the related issue.

**Comment by cjke** [comment]
No worries at all. Cool theme btw!
