### ISSUE TITLE
Python syntax highlighting

### ISSUE THREAD

**Issue by niijv** [akamud/vscode-theme-onedark#4]
![python-atom-vscode](https://cloud.githubusercontent.com/assets/5002330/13391242/8d059868-ded3-11e5-8771-ea408a917474.png)

Atom LEFT, VS Code RIGHT

Some small issues I found with python.
I like the small distinction atom has for "classmethod", but I guess that is preference.
The coloring of arguments though is really useful.

Thanks for porting the theme to VS Code!

**Comment by akamud** [comment]
Thanks for reporting, I'll look into it this weekend

**Comment by akamud** [comment]
This is now fixed in 0.2.2.
