### ISSUE TITLE
Dot notation with line breaks

### ISSUE THREAD

**Issue by iddan** [akamud/vscode-theme-onedark#40]
![image](https://cloud.githubusercontent.com/assets/12671072/22880563/50c80814-f1eb-11e6-8f1b-53a0500b3a00.png)

cells should be treated as an object (red).

```JavaScript
function Table({ columns, cells }) {
  columns.map(column => {
    return <div style={column.style}>{
      cells
        .filter(cell => cell.column === column.id)
    }</div>;
  });
}
```

**Comment by akamud** [comment]
Atom doesn't color it as red:
![image](https://cloud.githubusercontent.com/assets/954102/23093793/ada1fb8a-f5d3-11e6-87f4-508ab18e7af1.png)

Since I'm trying to keep this as close to Atom as possible this won't be changed.
