### ISSUE TITLE
Broken on VSCode 1.9.1

### ISSUE THREAD

**Issue by CharlieHess** [akamud/vscode-theme-onedark#41]
Updated to v1.2.0 of this theme, on VSCode 1.9.1. Now it's busted:

![](https://d3vv6lp55qjaqc.cloudfront.net/items/3k2t1L0t0l1i45330G3O/Image%202017-02-13%20at%206.11.20%20PM.png?X-CloudApp-Visitor-Id=1741631&v=2be57031)

Tried reinstalling, reloading, quitting, etc.

**Comment by CharlieHess** [comment]
Nevermind, apparently it just needs to be reselected in _Code > Preferences > Color Theme_. Seems like a VSCode bug instead.

**Comment by akamud** [comment]
Sorry about that, it is not a VSCode bug, it was caused by some internal changes I made on the extension. It shouldn't happen again in the future.

I'll update the README to avoid confusion in the next version.
