### ISSUE TITLE
Diff screen: can't clearly see changed commented lines.

### ISSUE THREAD

**Issue by Aukstkalnis** [akamud/vscode-theme-onedark#42]
When using this theme I cant clearly see difference in commented lines. Adjust a little bit color on diff screen for clear visibility.

**Comment by akamud** [comment]
Unfortunately theming in the diff panel is not possible at the moment. VSCode is improving the way we can theme other parts of the editor, so I'm always seeing how we can improve.

**Comment by akamud** [comment]
This is now better in version 2.0.0 with more support from VSCode. Please report if you find anything unusual.
