### ISSUE TITLE
TypeScript and TypeScriptReact template string problems

### ISSUE THREAD

**Issue by wilomgfx** [akamud/vscode-theme-onedark#43]
#It doesn't seem to take in consideration the presence of a variable inside the template string whilst using .ts(TypeScript Lang) or .tsx(TypeScript React)

![image](https://d3uepj124s5rcx.cloudfront.net/items/3y1k2a2D03320W2D0c1l/Image%202017-02-20%20at%2014.37.33.png?v=b69aa0da)

Thats where constants comes from 

```javascript

import * as constants from '../configs/constants'

```

Thanks :)!

**Comment by akamud** [comment]
Could you provide a full sample so I can test it here, please?

This happens in `.ts` and `.tsx` files?

**Comment by wilomgfx** [comment]
Seems like : constants is a reserved word or something, because its green when using it with ```.tsx```. 

I can change it to say : consts and it becomes red like the rest of the non local variables

Changing it to something else than constants fixed it. My bad! Sorry for wasting your time.

**Comment by akamud** [comment]
No problem. Thanks for reporting back.
