### ISSUE TITLE
Colorizing array's object keys or values

### ISSUE THREAD

**Issue by ridjis** [akamud/vscode-theme-onedark#44]
It would be better if color of object keys and values differ like in default monokai dimmed theme.

## Sample code

```javascript
const APP_ROUTES: Routes = [
  { path: '',           component: HomeComponent },
  { path: 'login',      component: LoginComponent },
  { path: 'profile',    component: ProfileComponent, canActivate:[AuthGuard] },
  { path: 'register',   component: RegisterComponent },
  { path: 'dashboard',  component: DashboardComponent, canActivate:[AuthGuard] }
];

@NgModule({
  declarations: [
    AppComponent,
    NavbarComponent,
    LoginComponent,
    RegisterComponent,
    HomeComponent,
    DashboardComponent,
    ProfileComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpModule,
    RouterModule.forRoot(APP_ROUTES),
    FlashMessagesModule
  ],
  providers: [
    ValidateService,
    AuthService,
    AuthGuard
  ],
  bootstrap: [AppComponent]
})
```

## Filename and Language selected

TypeScript

## VSCode theme Screenshot

![image](https://cloud.githubusercontent.com/assets/11313640/23169939/dd4c4e4a-f84d-11e6-836a-24699526f915.png)

## Versions used

* VSCode version: 1.9.1
* Theme version: 1.3.0

**Comment by akamud** [comment]
Thanks for contributing.

I noticed that Atom doesn't do this either:

![image](https://cloud.githubusercontent.com/assets/954102/24336291/bcd15c58-1262-11e7-9fd9-ed12b723ec53.png)

This is meant to be a port of the Atom coloring as close as possible, so I won't be fixing this because we would be changing the original theme.
