### ISSUE TITLE
Strange wrapper color around the code

### ISSUE THREAD

**Issue by elias-garcia** [akamud/vscode-theme-onedark#47]
## Sample code

http://pastebin.com/iXBpCV7Q

## Filename and Language selected

.ts extension and typescript language.

## Atom Original theme Screenshot

![Atom Screenshot](https://cloud.githubusercontent.com/assets/6737805/23551567/932229da-0017-11e7-8842-f753bd388278.png)

## VSCode theme Screenshot

![VSCode Screenshot](https://cloud.githubusercontent.com/assets/6737805/23551572/a1fc38f6-0017-11e7-8160-68bdd182fd87.png)

## Versions used

* VSCode version: 1.10.1
* Theme version: 1.3.1

## Extra information

As you can see in the screenshot, a strange wrapper appears around the code in VSCode in the same color that a selected line has. It changes dynamically as I scroll trough the code. I'm seeing this bug in an external screen connected trough HDMI to my Macbook Pro Retina 2015.

**Comment by akamud** [comment]
This has been reported in #33, it is a bug in VSCode itself, it is still open thought. You can see more info here: Microsoft/vscode#12473
