### ISSUE TITLE
Italic variant

### ISSUE THREAD

**Issue by tlvenn** [akamud/vscode-theme-onedark#49]
Similarly to https://github.com/TimoSta/one-dark-italic-syntax, it would be great to have an italic variant:

![italics](https://raw.githubusercontent.com/TimoSta/one-dark-italic-syntax/master/screenshots/jsx.png)

**Comment by akamud** [comment]
I don't plan on supporting themes other than the ones Atom provided at the moment. 

Since the code is MIT-licensed anyone can fork it and start from there :)

**Comment by tlvenn** [comment]
Fair enough @akamud ;) Thanks for the quick feedback.
