### ISSUE TITLE
Java script highlights only partially

### ISSUE THREAD

**Issue by PD75** [akamud/vscode-theme-onedark#5]
Hi,

There are large inconsistencies between atom and vscode for javascript for your one dark theme. I prefer more color to less. Left is Atom, right is vscode.

The important points for me are:
- Highlight function, to clearly see when I do function calls
- I would like all variables or objects not used as funtions in consistent color, notice how `line 33 var bottomMenu ` is highlighted in vscode, but not in Atom , while ` line 32 vm.bottomMenu ` is highlighted other way around.

/Paul
![image](https://cloud.githubusercontent.com/assets/10294795/13592595/ee7a4c8a-e4f3-11e5-836c-bdab5b62acdf.png)

**Comment by PD75** [comment]
Just wanted to add, that the key point is to clearly see all objects in a  hierarchy, different color in special characters and object/variables names is the key.

**Comment by akamud** [comment]
Thank you for reporting this, is that code open source? I could use it as an example to make sure I got everything right.

**Comment by PD75** [comment]
Quick respons, thx:

Code is here:
[practical-startpage](https://github.com/PD75/practical-startpage)
The file I showed is WIP but this file will give similar layout: [editLayout](https://github.com/PD75/practical-startpage/blob/master/appdev/app/core/options/editLayout.js)

![image](https://cloud.githubusercontent.com/assets/10294795/13603124/43000f82-e53b-11e5-91b8-1c713c3c4d8d.png)

**Comment by akamud** [comment]
Thanks, I'll look into it ASAP.

**Comment by PD75** [comment]
@akamud, I saw you tagged this up for grabs. Would you mind giving me a short intro to how the code work have never written a plugin, maybe I can do some changes on the fly while I code?

**Comment by akamud** [comment]
I started working on this but didn't finish yet.

When you install a theme, it will be installed in your user folder/.vscode/extensions. In there you will find akamud.vscode-theme-onedark-0.2.2/themes/One%20Dark.tmTheme.

If you change that file and restart VSCode you will get the updated theme.

In this file you will find a bunch of XML nodes like this

```XML
<dict>
    <key>name</key>
    <string>Type Name</string>
    <key>scope</key>
    <string>entity.name.type</string>
    <key>settings</key>
    <dict>
        <key>foreground</key>
        <string>#e5c07b</string>
    </dict>
</dict>
```

Each node like that corresponds to a token coloring. The two important things are the `scope` and the `foreground` nodes.  
The scope is used to tell to which tokens the rule being declared will be applied.  
The foreground tells the color to apply.

You can find the scope using the Developer Tools inside VSCode (Help > Toggle Developer Tools) and then inspecting the desired element. You will see the token has many CSS classes applied, these CSS classes are your scope.

I plan to write a "Contributing" file explaining this better.

**Comment by PD75** [comment]
@akamud, thanks. 

A thought, can I treat the strings as css/DOM statements, and flip around the classes etc. like:
- entity.name
- entity.type
- entity.type.name

BTW, I will wait for your updates so we don't do double job, then I can work to fine tune.

**Comment by akamud** [comment]
Yes, the order of the classes doesn't matter.

**Comment by akamud** [comment]
After reviewing the tokens, I noticed that many of the tokens Atom colorize isn't available on VSCode, which is unfortunate. That means there is no way of differentiating the tokens to colorize it without changing all the other tokens' colors.

For example:
`angular` in `angular.module` does not have anything that differentiate itself from a regular token in JS, so if I change its color to red, you will have a JS file with a bunch of red tokens, which is really bad.

You can see the Dark+ theme as a reference to which tokens are available in VSCode.

With that said, I released a new version (0.2.5) fixing some tokens that were indeed wrong. But right now that's the closest we can get to Atom's theme in JS. VSCode is constantly improving its color scheme, so maybe this will get better in future updates.

**Comment by PD75** [comment]
@akamud, thanks for the effort, I will keep an eye out if things changes in vscode and try some changes.

**Comment by akamud** [comment]
Feel free to send a feedback if you find anything that we can improve.
