### ISSUE TITLE
export default highlighting

### ISSUE THREAD

**Issue by iddan** [akamud/vscode-theme-onedark#52]
`default` is a keyword and should be highlighted in purple.

## Sample code

```
export default a;
```

## Filename and Language selected

.js
JavaScript React

## VSCode theme Screenshot

![screen shot 2017-04-06 at 17 32 30](https://cloud.githubusercontent.com/assets/12671072/24759755/39391f30-1aef-11e7-862d-b0a46783b098.png)

## Versions used

* VSCode version: 1.11.0
* Theme version: 1.3.2

**Comment by akamud** [comment]
Sorry for taking so long answering this.

Atom highlights exactly the same as VSCode. Since this is a port, I don't plan on changing this behavior.

Atom:
![image](https://user-images.githubusercontent.com/954102/28499441-875407f6-6f8c-11e7-80b0-fd5347ac4abd.png)
