### ISSUE TITLE
C# variable declaration colour should be swapped with normal variable colour

### ISSUE THREAD

**Issue by GarrettShields** [akamud/vscode-theme-onedark#53]
In Atom when declaring a variable the colour is red and normal variable use is white. Right now in VS Code (for C#) it's the opposite, white when declaring and red for normal use.

## Sample code
```
public class MyClass
{
    private const float float1 = 10f;
    private float float2 = 0f;

    private void Update()
    {
        while(float2 > float1)
            float2 += Time.deltaTime;
    }
}
```

## Atom Original theme Screenshot
https://puu.sh/vbZux/3ab94a46d8.png
![atom_2017-04-07_00-01-58](https://cloud.githubusercontent.com/assets/3299915/24785338/0710ccfa-1b27-11e7-8be6-321c8b1d02c7.png)

## VSCode theme Screenshot
https://puu.sh/vbZtG/9e7f07f183.png
![code_2017-04-07_00-01-38](https://cloud.githubusercontent.com/assets/3299915/24785342/0f9871e8-1b27-11e7-9863-9bc5b4365a10.png)

## Versions used
* VSCode version: 1.11.1
* Theme version: 1.3.2

## Extra information
Other plugins I'm using.
C# https://marketplace.visualstudio.com/items?itemName=ms-vscode.csharp
Rainbow Brackets https://marketplace.visualstudio.com/items?itemName=2gua.rainbow-brackets
Unity Tools https://marketplace.visualstudio.com/items?itemName=Tobiah.unity-tools

**Comment by akamud** [comment]
Thanks for reporting, this is now much better in 2.0.3.

Some inconsistencies are not possible to fix due to VSCode tokenizer.

This is how it looks in 2.0.3:
![image](https://user-images.githubusercontent.com/954102/28499552-ebc08bd6-6f8e-11e7-9090-5727d7f09839.png)
