### ISSUE TITLE
class (public) properties highlighting

### ISSUE THREAD

**Issue by iddan** [akamud/vscode-theme-onedark#54]
**Please provide as much information as possible, usually I need these information to actually start working on an issue, so try to fill as much of these as possible**

## Sample code

```JavaScript
export class DatePickerInput extends React.Component {
  state = {
    showOverlay: false,
    value: '',
    selectedDay: null
  };
}
```

## Filename and Language selected

filename: DatePickerInput.js
lang: JavaScriptReact

## VSCode theme Screenshot

![screen shot 2017-04-09 at 15 10 15](https://cloud.githubusercontent.com/assets/12671072/24837198/f6640522-1d36-11e7-91b4-5ff026d835f0.png)

## Versions used

* VSCode version: 1.11.1
* Theme version: 1.3.2

## Extra information
https://babeljs.io/docs/plugins/transform-class-properties/

**Comment by akamud** [comment]
Thanks for reporting.

This is fixed in 2.0.3.
