### ISSUE TITLE
Cursor transparency

### ISSUE THREAD

**Issue by jamesgecko** [akamud/vscode-theme-onedark#55]
## Sample code

```
  def show
    respond_with @report
  end
```

## Filename and Language selected
`report_controller.rb`
Ruby

## Atom Original theme Screenshot

<img width="180" alt="screen shot 2017-04-13 at 11 02 58 am" src="https://cloud.githubusercontent.com/assets/44252/25010687/db628668-2038-11e7-9a7e-0ec46e0bf599.png">

## VSCode theme Screenshot

<img width="185" alt="screen shot 2017-04-13 at 11 02 43 am" src="https://cloud.githubusercontent.com/assets/44252/25010674/d592860c-2038-11e7-865d-5f4f898187dc.png">

## Versions used

* VSCode version: 1.11.1
* Theme version: 1.3.2

## Extra information

Are color theme extensions allowed to modify CSS? There's a PR that added more cursor styles to VSCode [here](https://github.com/Microsoft/vscode/pull/14237).

**Comment by akamud** [comment]
Thanks for reporting this. Unfortunately there is no way of providing transparency to the cursor at the moment. I opened an [issue](https://github.com/Microsoft/vscode/issues/28008), if they release this I'll get back to this and update the theme.

**Comment by akamud** [comment]
I think this was an oversight from my part. I'll update this in the next version.

**Comment by akamud** [comment]
How did you make Atom's cursor show as a block? I want to investigate this to see exactly the same colors.

**Comment by jamesgecko** [comment]
The block cursor in that screenshot is from the [`vim-mode-plus` extension](https://github.com/t9md/atom-vim-mode-plus). While trying to come up with a quick thing you could dump into Atom's `styles.less` config to fatten the cursor up without installing the extension, I discovered that all the transparency is coming from the extension!

It's basically doing this for a block cursor
```less
atom-text-editor .cursor {
  border-width: 1vh;
  opacity: 0.5 !important;
}
```

But while the cursor is in narrow mode, it doesn't have any opacity at all. This is probably an option I should query the [VsCodeVim](https://github.com/VSCodeVim/Vim) people about. Sorry for the trouble!

**Comment by akamud** [comment]
No problem!

I don't plan on supporting extensions scenarios because this would impact people using it without extensions, and I want this theme to be as close as possible to Atom's original theme.

I'm closing this for now, thanks for contributing.
