### ISSUE TITLE
Workbench custom colors

### ISSUE THREAD

**Issue by rafaelpimpa** [akamud/vscode-theme-onedark#56]
VSCode 1.12 version is now live and the ``workbench.colorCustomizations`` is now ready to use. Was messing around and came up with this:

![onedark](https://cloud.githubusercontent.com/assets/18370605/25727606/7ca37802-3100-11e7-88ee-aea4e47c0ece.png)

Some minor things to work but I'm gonna use it like that until you update.

The code:

```json
"workbench.colorCustomizations": {
    "tab.activeBackground": "#282c34",
    "tab.inactiveBackground": "#2f333f",
    "activityBar.background":"#282c34",
    "editorGroup.background": "#282c34",
    "sideBar.background": "#202329",
    "sideBarSectionHeader.background": "#2f333f",
    "list.hoverBackground": "#2f333f",
    "list.activeSelectionBackground": "#2f333f",
    "list.inactiveSelectionBackground": "#282c34",
    "statusBar.background": "#181a1f",
    "statusBarItem.hoverBackground": "#2f333f",
    "input.background": "#393d48",
    "editorGroupHeader.tabsBackground": "#202329"
}
```

Hope it helps with something ;)

**Comment by rkostrzewski** [comment]
@rafaelpimpa I've also hacked together One Dark like theme - this one comes with styled widgets like find & replace, editor suggestions etc.

You can find it here: https://gist.github.com/rkostrzewski/29aaa988c5ab982f71b62d8dc6edd5e8 (scroll down for screenshot comparision)

Might be good starting point.

**Comment by akamud** [comment]
Thank you so much for taking the time and sharing this. This was a great starting point.

I'm happy to say that version 2.0.0 of [One Dark](https://marketplace.visualstudio.com/items?itemName=akamud.vscode-theme-onedark) and [One Light](https://marketplace.visualstudio.com/items?itemName=akamud.vscode-theme-onelight) are now out and provide workbench theming. From my tests, this theme is the closest to Atom's original theme in the marketplace.

Please let me know if you find anything unusual in the new version.
