### ISSUE TITLE
Inconsistency in javascript Object methods

### ISSUE THREAD

**Issue by lerran80** [akamud/vscode-theme-onedark#57]
## Sample code
const a = [...Object.keys(b)]
const c = Object.keys(b)

## Filename and Language selected
Extension is .js for javascript

## Atom Original theme Screenshot
![screen shot 2017-05-16 at 11 51 06](https://cloud.githubusercontent.com/assets/22422447/26112318/00e12cc8-3a2e-11e7-93b1-f444aa987a49.png)

## VSCode theme Screenshot
![screen shot 2017-05-16 at 11 39 31](https://cloud.githubusercontent.com/assets/22422447/26112630/d8aa7a24-3a2e-11e7-8323-3ae2f179a7f0.png)

## Versions used
* VSCode version: 1.12.2
* Theme version: 1.3.2

## Extra information
No other plugins affecting js.

Cheers!

**Comment by akamud** [comment]
Thanks for reporting. This is fixed in 2.0.3.

The only problem is that the `const` name can't be colored the same as Atom due to a difference in VSCode tokenization.

![image](https://user-images.githubusercontent.com/954102/28499742-3c211f9c-6f93-11e7-8252-9759f30fd43e.png)
