### ISSUE TITLE
Indent Guides Missing in v2

### ISSUE THREAD

**Issue by imcotton** [akamud/vscode-theme-onedark#58]
With `editor.renderIndentGuides: true`

## Sample code

```javascript
function foobar () {
    for (const i of [1, 2, 3]) {
        console.info(i);
    }
}
```

## Filename and Language selected

`JavaScript`, `TypeScript`, `JSON`

## VSCode theme Screenshot

![screen shot 2017-06-05 at 16 04 16](https://cloud.githubusercontent.com/assets/149541/26775811/1b133aec-4a09-11e7-9097-76e4e14da3ee.png)

## Versions used

* VSCode version: 1.12.2
* Theme version: 2.0.0

**Comment by akamud** [comment]
Thank you for reporting, this is now fixed in 2.0.1.
