### ISSUE TITLE
Visible whitespace too brightly colored 

### ISSUE THREAD

**Issue by TheSpiritXIII** [akamud/vscode-theme-onedark#59]
Hello, I have received the upgrade recently and I noticed there was something distracting me. I made before/after screenshots. In short, visible whitespace is too bright. It used to look fine before.

Before:
![image](https://cloud.githubusercontent.com/assets/4027687/26808915/6ebe8d2a-4a2e-11e7-89aa-f1fdb3fce7ac.png)

After:
![image](https://cloud.githubusercontent.com/assets/4027687/26808920/8218309c-4a2e-11e7-8854-bc35270802b0.png)

Notice how it is a light grey now and does not match Atom anymore:
![image](https://cloud.githubusercontent.com/assets/4027687/26808936/9fb5ac42-4a2e-11e7-9acb-7136da511a31.png)

## Versions used

* VSCode version: 1.12.2
* Theme version: 2.0.1

## Extra information

In the provided screenshot, I am using the Rust language plugin, but I have also noticed this at my work computer where I use JavaScript.

**Comment by akamud** [comment]
You are right, I screwed up these colors. Thanks for reporting, I'll fix this in 2.0.2 and I'll let you know when it is released.

**Comment by akamud** [comment]
This is now released in 2.0.2.
