### ISSUE TITLE
Wrong Rust impl highlighting

### ISSUE THREAD

**Issue by jkcclemens** [akamud/vscode-theme-onedark#62]
**Please provide as much information as possible, usually I need these information to actually start working on an issue, so try to fill as much of these as possible**

## Sample code

```rust
impl Something for AnotherThing {
  
}
```

## Filename and Language selected

.rs/Rust

## Atom Original theme Screenshot

![atom](http://i.imgur.com/VnmnSv2.png)

## VSCode theme Screenshot

![vscode](http://i.imgur.com/ap0vhxb.png)

## Versions used

* VSCode version: 1.13.0
* Theme version: 2.0.2

## Extra information

Recently broken. This was working correctly up until less than a week ago.

**Comment by akamud** [comment]
I'm sorry, something changed in VSCode then. It uses the same token for these two scenarios:

![image](https://user-images.githubusercontent.com/954102/28499768-e4dc25fa-6f93-11e7-91b5-0f8dbd823d8c.png)

![image](https://user-images.githubusercontent.com/954102/28499770-eb54b942-6f93-11e7-906b-d017f8405b1d.png)

From my understanding and from looking at Atom, `HasLifetime` should be colored yellow. So if I fix the issue with your example, I'll break everything else.

I'm assuming this is less annoying then having everything gray. What do you think?

**Comment by jkcclemens** [comment]
Yeah, leaving it is fine. Nothing you can really do!
