### ISSUE TITLE
PHP Syntax Issue

### ISSUE THREAD

**Issue by lloydstubber** [akamud/vscode-theme-onedark#63]
## Sample code

<?php if (have_posts()) : while (have_posts()) : the_post(); ?>
           <h1><?php the_title(); ?></h1>
           <?php the_content(); ?>
<?php endwhile; endif; ?>

## Filename and Language selected

File name: page.php
Lang: PHP

## Atom/VSCode Screenshot

![php-issue](https://user-images.githubusercontent.com/18339250/27206057-109f35f8-5278-11e7-8391-cadddca2e434.jpg)

## Versions used

* VSCode version: 1.13.1
* Theme version: 0.4.3

**Comment by akamud** [comment]
Can you please update to VSCode 2.0+?

It looks like it is fixed already.

![image](https://user-images.githubusercontent.com/954102/28499792-936bd2b4-6f94-11e7-83d4-d6de412ef551.png)
