### ISSUE TITLE
Color inconsistency

### ISSUE THREAD

**Issue by abdonrd** [akamud/vscode-theme-onedark#64]
I want to provide some screenshots about color inconsistency.

#### URLs in `.html` files

<img width="1440" alt="screen shot 2017-06-16 at 2 32 03 am" src="https://user-images.githubusercontent.com/1007051/27207756-54bfe80e-5241-11e7-9f7b-605083555238.png">

#### `module.exports` in `.js` files

<img width="1440" alt="screen shot 2017-06-16 at 2 32 31 am" src="https://user-images.githubusercontent.com/1007051/27207764-69159bdc-5241-11e7-918d-66f5dd3cefe9.png">

#### URLs and code blocks in `.md` files

<img width="1440" alt="screen shot 2017-06-16 at 2 32 58 am" src="https://user-images.githubusercontent.com/1007051/27207770-80fa830c-5241-11e7-9bc2-dd7bb38e6644.png">

#### URLs, Booleans and nulls in `.json` files

<img width="1440" alt="screen shot 2017-06-16 at 2 33 57 am" src="https://user-images.githubusercontent.com/1007051/27207780-94252338-5241-11e7-8e52-bed6175700d3.png">

<img width="1440" alt="screen shot 2017-06-16 at 2 35 04 am" src="https://user-images.githubusercontent.com/1007051/27207789-a90ea012-5241-11e7-867f-f694d528b339.png">

#### `WCT.loadSuites()`, `Polymer.` and `static get` in `.html` files (insides `<script>` tag)

<img width="1440" alt="screen shot 2017-06-16 at 2 36 48 am" src="https://user-images.githubusercontent.com/1007051/27207810-d403d242-5241-11e7-9610-9e7211690550.png">

<img width="1440" alt="screen shot 2017-06-16 at 2 39 28 am" src="https://user-images.githubusercontent.com/1007051/27207838-0baa1c74-5242-11e7-9780-22ec4d8eae9e.png">

## Versions used

* VSCode version: 1.13.0
* Theme version: 2.0.2

## Extra information

I'm using [Polymer IDE plugin](https://marketplace.visualstudio.com/items?itemName=polymer.polymer-ide).

**Comment by abdonrd** [comment]
Any news on this?

I just saw that the `OneDark.json` is minified. Can you beautify to allow easy PRs?

**Comment by akamud** [comment]
Thanks for your patience, I've been busy in the last months and didn't have a chance to look at your PR yet.

The reason the json is minified is because I actually auto generate them from Atom itself. So when someone opens a PR, I have to read the changes and repeat them in my generator.

I plan on making opening PRs easier, but didn't have the time yet.

**Comment by abdonrd** [comment]
Okay, I'll wait. Thanks!

And maybe you can add the generator to the repository.

**Comment by akamud** [comment]
I'm planning on doing that too. I feel that the code is not mature enough to be open source just yet, it needs some more infrastructuring and automations.

**Comment by akamud** [comment]
Ok, some changes are now in version 2.0.4.

Thank you for taking the time sending all these screenshots.

Some things I could not fix:
* URLs can't be customized per language, VSCode uses the same URL color for everything. Having it shown as the same color as string's color is the one that makes for less color disruption at the moment.
* Markdown URLs are recognized as the same token as the text before it, so I can't customize just the URL link colors.
* Same problem with JSON URLs.
* The `Polymer` variable has a token that is too generic, I can't change it without causing a bunch of side-effects. But the `WCT` and `get` inconsistencies are now fixed.
