### ISSUE TITLE
Change color of extension buttons

### ISSUE THREAD

**Issue by ajitid** [akamud/vscode-theme-onedark#65]
![capture](https://user-images.githubusercontent.com/26769888/27264423-9e170d50-549b-11e7-8015-039d811b9a26.PNG)
These can be colored with:-

		"extensionButton.prominentBackground"
		"extensionButton.prominentForeground"
		"extensionButton.prominentHoverBackground"

**Comment by akamud** [comment]
Thanks for reporting. I'll fix this in the next release.

**Comment by akamud** [comment]
I changed them to look like Atom's `btn-success`. Thank your for letting me know.

You can see these changes in 2.0.4.
