### ISSUE TITLE
Switch logo image to other than SVG

### ISSUE THREAD

**Issue by JimiC** [akamud/vscode-theme-onedark#66]
Upcoming `vscode` will block `SVG` images. The latest `vscode-vsce` tool (`1.27.0`) also blocks publishing `SVG` images to the marketplace.

**Comment by akamud** [comment]
Thank you for the heads up! Next release will have PNG image again.

**Comment by akamud** [comment]
Keeping track of all the changes that needed to be done: https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_14.md#changes-for-extension-authors

**Comment by akamud** [comment]
Fixed all the issues in 2.0.3.
