### ISSUE TITLE
Terminal selector

### ISSUE THREAD

**Issue by umpirsky** [akamud/vscode-theme-onedark#67]
Not sure if part of the theme, but terminal selector looks like it does not belong here:

![screenshot from 2017-07-04 20-34-04](https://user-images.githubusercontent.com/208957/27840347-614c5f10-60f8-11e7-8a76-4785a38ee1be.png)

Color is odd.

**Comment by akamud** [comment]
Is this when the dropdown is focused?

**Comment by akamud** [comment]
I just confirmed this is when the dropdown is focused.

Unfocused:
![image](https://user-images.githubusercontent.com/954102/27842044-85ba7312-60dc-11e7-9127-48c6edff1df3.png)

Focused:
![image](https://user-images.githubusercontent.com/954102/27842046-8a9d02c8-60dc-11e7-8d82-407ea2bde25a.png)

Indeed Atom does not use the blue outline, it remains black:
![image](https://user-images.githubusercontent.com/954102/27842097-2202de94-60dd-11e7-9a43-ac104f5fd958.png)

 I'll fix this in the new version.

Thanks for reporting!

**Comment by umpirsky** [comment]
@akamud It's not just blue, it's the bg color of select options as well.

**Comment by akamud** [comment]
I don't get the bg color part. As you can see from the screenshot above it has the same color as Atom, with the same contrast.

Could you elaborate more, please?

**Comment by umpirsky** [comment]
![screenshot from 2017-07-05 16-18-54](https://user-images.githubusercontent.com/208957/27868653-
ae22a600-619d-11e7-8432-9ddce00a9986.png)

@akamud I't not the same:

Atom: #3A3F4B
Code: #43484D

**Comment by akamud** [comment]
Oh I see, I'll see if there is a way of customizing this control. 

Thanks for taking the time reporting this.

**Comment by akamud** [comment]
Ok, finally had the time to fix this. Background color now is the same as Atom.

Released in 2.0.4.

Thank you for your help and patience.
