### ISSUE TITLE
Rust `unsafe` keyword is the wrong color

### ISSUE THREAD

**Issue by aloucks** [akamud/vscode-theme-onedark#70]
It's currently highlighted with `#C678DD` but it should be `#E06C75`

This is how it looks in Atom:

![image](https://user-images.githubusercontent.com/221559/29736474-87436f56-89cf-11e7-870a-581f61f32ea1.png)

Workaround:

settings.json:

    "editor.tokenColorCustomizations": {
        "textMateRules": [
            {
                "scope": "keyword.other.unsafe.rust",
                "settings": {
                    "foreground": "#E06C75"
                }
            }
        ]
    }

**Comment by akamud** [comment]
Thank you for opening the issue and sending the fix.

This is now released in version 2.0.4.
