### ISSUE TITLE
ERROR syntax wrong color?

### ISSUE THREAD

**Issue by th0tt** [akamud/vscode-theme-onedark#72]
Hi,

When using atom dark theme ERROR syntax is highlighted as green color instead of red.
Is this supposed to look like this?
![image](https://user-images.githubusercontent.com/18008933/30423350-dd1a550c-9942-11e7-984b-fcd5111e5680.png)

WARNING syntax seems to be correct, it is showing in red.
![image](https://user-images.githubusercontent.com/18008933/30423011-daf7c15c-9941-11e7-9a74-5d811e5f89ee.png)

And is it possible to set ERROR, WARNING as bold text?

This is how it looks with default theme:
![image](https://user-images.githubusercontent.com/18008933/30423411-004c07e6-9943-11e7-8f01-f0a144c2c8a2.png)

**Comment by akamud** [comment]
Is this in the console window?

**Comment by th0tt** [comment]
No, the "Main" Window.

**Comment by akamud** [comment]
Can you show a screenshot of the whole window? I don't get where this message is coming from.

**Comment by th0tt** [comment]
Ah sorry, this is a application error log and has nothing to do with the theme or visual studio code.

What I mean with the issue is that ERROR syntax has green color and I was wondering if it is possible to set it to red color so it looks like WARNING syntax shown in the second screenshot.

**Comment by akamud** [comment]
Yeah, but I still don't understand where this output is from.

To answer your question I need to inspect the text to see who is changing the color. And right now I don't know where this text is presented.

**Comment by th0tt** [comment]
I think I found the problem in the extension Log File Highlighter.
I will contact the developer and see if he can fix it that way instead.
