### ISSUE TITLE
Incorrect Python colors

### ISSUE THREAD

**Issue by grantmcconnaughey** [akamud/vscode-theme-onedark#73]
**Please provide as much information as possible, usually I need these information to actually start working on an issue, so try to fill as much of these as possible**

## Sample code

```python
if x is True or x is None:
    x = False
```

## Filename and Language selected

.py/Python

## Atom Original theme Screenshot

![image](https://user-images.githubusercontent.com/4023140/30710146-3b4fc6f2-9eca-11e7-8cf0-84f81d0c042f.png)

## VSCode theme Screenshot

![image](https://user-images.githubusercontent.com/4023140/30710154-4327a5e8-9eca-11e7-8e4d-9c01fe3660af.png)

## Versions used

* VSCode version: 1.16.1
* Theme version: 2.0.3

## Extra information

`None`, `True`, and `False` are an incorrect color in Python 3.

**Comment by grantmcconnaughey** [comment]
Actually, it looks like this is fixed in https://github.com/akamud/vscode-theme-onedark/pull/51.

**Comment by akamud** [comment]
Thank you for submitting the issue. The PR is fine, I'm struggling to find time to release a new version, but I'll let you know when it is released.

**Comment by grantmcconnaughey** [comment]
I understand! I've made the change locally for now, so no rush.

Thanks for taking the time to make this extension it in the first place.

**Comment by akamud** [comment]
This is now fixed in 2.0.4.
