### ISSUE TITLE
Increase indent in file explorer

### ISSUE THREAD

**Issue by realuser** [akamud/vscode-theme-onedark#75]
How can I configure the indent of files inside folders within the sidebar file explorer?

Currently, the indent is too small so it's hard for me to see whether files are part of a folder or not.  I would like to be able to increase this indent a user configurable amount.

For example, in the below screen shot it's difficult for me to quickly see that:
1. The properties folder is open
2. AssemblyInfo.cs is inside the properties folder

![vs-code-file-explorer-indent](https://user-images.githubusercontent.com/7472570/31052269-db31cb2c-a634-11e7-9e38-005fdcbcced5.jpg)

## Versions used

* VSCode version: 1.16.1
* Theme version: 2.0.5

**Comment by akamud** [comment]
I'm sorry, this has nothing to do with One Dark theme. Icons are provided by other themes, One Dark does not interfere in any way.
