### ISSUE TITLE
Inconsistency with the for...in loop in Javascript

### ISSUE THREAD

**Issue by zl-kolev** [akamud/vscode-theme-onedark#79]
Very well done! You have managed to recreate the Atom One Dark theme we all know and love to a very high degree of precision.

Now this regards Javascript. In Atom the for...in loop the "for" and "in" keywords are in the same color which is purple and in your theme the "for" is purple and the "in" is turquoise, like "isNaN" and ".round". Can you please make the "for" and "in" words the same purple color, please. That will be well appreciated!

## Sample code

```
for (loopCounter in degCent) {
	if (isNaN(degFahren[loopCounter])) {
	document.write("Value " + loopCounter + " which is " + "\"" + degFahren[loopCounter] + "\"" + " is invalid." + "<br>");
	continue;
}
```

## Filename and Language selected

I am creating a standard Javascript file with the .js file extension.

## Atom Original theme Screenshot (left) and VSCode theme Screenshot (right)

![atom-vscode-one-dark-theme-for-in-loop-inconsistency](https://user-images.githubusercontent.com/31390751/31689678-daf0dbdc-b398-11e7-93c0-83fd002ba207.jpg)

## 

## Versions used

* VSCode version: 1.17.2, Windows 10 64-bit
* Theme version: 2.0.5

## Extra information

I have no other relevant plugins or extensions that are in conflict with the theme.

**Comment by akamud** [comment]
Thank you for taking the time reporting this.

This is now fixed in version 2.0.6.
