### ISSUE TITLE
Inconsistency with a date object used as an array index number in Javascript

### ISSUE THREAD

**Issue by zl-kolev** [akamud/vscode-theme-onedark#81]
Now this regards Javascript again. In Atom, when a date object is used as an array index number, it is colored in red. In VSCode, it appears light orange, like a new object. Can you make them the same red color, please. That will be well appreciated!

## Sample code

```
	function displayTimeNow() {
		var currentTime = new Date();
		var months = ["януари", "февруари", "март", "април", "май", "юни", "юли",	"август", "септември", "октомври", "ноември", "декември"];
		var daysWeek = ["понеделник", "вторник", "сряда", "четвъртък", "петък", "събота", "неделя"];
		var currentMonth = months[currentTime.getMonth()];
		var currentDay = daysWeek[currentTime.getDay()];
		document.getElementById("output-day").innerHTML =  currentDay + "," + "&nbsp";
		document.getElementById("output-hours").innerHTML = currentTime.getHours() + "&nbsp" + ":" + "&nbsp";
		document.getElementById("output-minutes").innerHTML = currentTime.getMinutes() + "&nbsp" + ":" + "&nbsp";
		document.getElementById("output-seconds").innerHTML = currentTime.getSeconds() + "&nbsp" + "часа" + "&nbsp" + "на" + "&nbsp";
		document.getElementById("output-date").innerHTML = currentTime.getDate() + "&nbsp";
		document.getElementById("output-month").innerHTML = currentMonth + "&nbsp";
		document.getElementById("output-year").innerHTML = currentTime.getFullYear() + " година";
	}
```

## Filename and Language selected

I am creating a standard Javascript file with the .js file extension.

## VSCode and Atom Original theme Screenshot

VSCode theme Screenshot (left) and Atom Original theme Screenshot (right), focus your attention on the red rectangles I have drawn for your convenience:
![atom-vscode-one-dark-theme-date-object-with-property-used-as-array-element-inconsistency](https://user-images.githubusercontent.com/31390751/33236040-4e77f6a0-d250-11e7-9f53-bf1163e1d948.jpg)

## Versions used

* VSCode version: 1.18.1
* Theme version: 2.1.0

## Extra information

I have no other relevant plugins or extensions that are in conflict with the theme.

**Comment by akamud** [comment]
Thanks for reporting. I'll take a look at this as soon as possible and release a new version.

**Comment by zl-kolev** [comment]
This issue seems fixed, you can close it if you want.

**Comment by akamud** [comment]
Investigating this issue I found out that, in this case:

```js
var currentDay = daysWeek[currentTime.getDay()];
const a = [...Object.keys(b)];
```

`Object` and `currentTime` are attributed the same scope ins VSCode, so I can't distinguish them. 

Atom can, so it shows them differently:

![image](https://user-images.githubusercontent.com/954102/36150200-0a78bafa-10aa-11e8-9c63-2e30705fb42b.png)

But in VSCode I can't change one without changing the other:

![image](https://user-images.githubusercontent.com/954102/36150223-18ee7660-10aa-11e8-99cc-62af74daffda.png)
