### ISSUE TITLE
highlighting for selection in text are not obvious

### ISSUE THREAD

**Issue by cateyes99** [akamud/vscode-theme-onedark#82]
## Sample code
It's in **any** languages, so a piece of **plain text** actually serve this demo the best as no other colour distracting. Let's say we have the below **plain text**:
```
{
    "parameters": [
        {
            "name": "@systemOfRecord",
            "value": "DATARICH"
        },
        {
            "name": "@searchEffectiveDate",
            "value": "2017-08-22"
        },
        {
            "name": "@lastName",
            "value": "Smith"
        },
```
Now select the `nam` in the first `name`:
## VSCode's Atom One Dark theme Screenshot
![image](https://user-images.githubusercontent.com/19678455/34807000-16221906-f6eb-11e7-8ba5-6954ca8b2170.png)
In the above screenshot, the highlighting in Line 8 & 12 aren't obvious, **hard** to spot!

## VSCode's Dark+ theme Screenshot
![image](https://user-images.githubusercontent.com/19678455/34807076-84f9ec0a-f6eb-11e7-858b-5f0f911a9e9d.png)
Here in the above one, the highlighting in Line 8 & 12 in the above screenshot are obvious, **easy** to spot!

## Versions used

* VSCode version: 1.19.2
* Theme version: 2.1.0

**Comment by akamud** [comment]
This is better now in 2.2.0.

![image](https://user-images.githubusercontent.com/954102/76765907-f22b9b00-6775-11ea-85d7-61ef4d672aa3.png)
