### ISSUE TITLE
Inconsistency with JavaScript template literals - flow type

### ISSUE THREAD

**Issue by charles8xu** [akamud/vscode-theme-onedark#87]
## Sample code
Extract from https://github.com/facebook/react/blob/master/packages/react-reconciler/src/ReactFiberClassComponent.js#L65

```javascript
function(callback: mixed, callerName: string) {
  if (callback === null || typeof callback === 'function') {
    return;
  }
  const key = `${callerName}_${(callback: any)}`;
  if (!didWarnOnInvalidCallback[key]) {
    warning(
      false,
      '%s(...): Expected the last optional `callback` argument to be a ' +
        'function. Instead received: %s.',
      callerName,
      callback,
    );
    didWarnOnInvalidCallback[key] = true;
  }
};
```

## Filename and Language selected

Using `.js` extension with `JavaScript` file type selected

## VSCode theme Screenshot

![image](https://user-images.githubusercontent.com/6831013/36982612-3bdf9e16-20cb-11e8-8999-af25648e6112.png)

## Versions used

* VSCode version: 1.20.1
* Theme version: 2.1.0

**Comment by akamud** [comment]
Thanks for submitting this.

Found out this is actually a bug in VSCode. Using the default theme gives me the same weird result. Would you mind reporting to the [tmLanguage repo](https://github.com/Microsoft/TypeScript-TmLanguage) from Microsoft?

It should be automatically fixed for my theme when they release a new version of the tmLanguage.

**Comment by charles8xu** [comment]
Like what https://github.com/Microsoft/TypeScript-TmLanguage/issues/577#issuecomment-370895838 said, it is not a valid javascript or typescript which is what the repo supports for colorizing.
